config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :contact_forms, only: [:new, :create, :destroy]
    root :to => "contact_forms#new"
    get "/contact" => "contact_forms#new"
  end
  match '*a', :to => 'error_pages#routing', via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_form.rb
class ContactForm < ApplicationRecord
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  
  after_create_commit do 
    ContactMailer.contact_us(self.id).deliver_later!
  end

  def full_name
    first_name +' '+ last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  rescue_from ActionController::RoutingError, :with => :render_404
  rescue_from ActionController::RoutingError, with: :route_not_found
  
  private
  def render_404(exception = nil)
    if exception
      logger.info "Rendering 404: #{exception.message}"
    end
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
  def set_locale
    # I18n.locale = params[:locale] || I18n.default_locale
    locale = params[:locale].to_s.strip.to_sym
    I18n.locale = I18n.available_locales.include?(locale) ? locale :
      I18n.default_locale
  end
  def default_url_options(options = {})
    {locale: I18n.locale}
  end
  
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  
 def new
    @contact_form = ContactForm.new
  end

  def create
    @contact_form = ContactForm.new(contact_form_params)
    respond_to do |format|
      if @contact_form.save
        format.html { redirect_to root_path, notice: "Contact form was successfully created." }
        format.json { render :show, status: :created, location: @contact_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def contact_form_params
      params.permit(:first_name, :last_name, :email, :phone, :message)
    end
end

app/controllers/error_pages_controller.rb
class ErrorPagesController < ApplicationController
  def routing
  	render_404
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/helpers/error_pages_helper.rb
module ErrorPagesHelper
end

app/views/contact_forms/index.html.erb
<p id="notice"><%#= notice %></p>

<h1>Contact Forms</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_forms.each do |contact_form| %>
      <tr>
        <td><%= contact_form.first_name %></td>
        <td><%= contact_form.last_name %></td>
        <td><%= contact_form.email %></td>
        <td><%= contact_form.phone %></td>
        <td><%= contact_form.message %></td>
        <td><%= link_to 'Show', contact_form %></td>
        <td><%= link_to 'Edit', edit_contact_form_path(contact_form) %></td>
        <td><%= link_to 'Destroy', contact_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Form', new_contact_form_path %>


 

app/views/contact_forms/new.html.erb
<div class="container-contact100">
  <div class="wrap-contact100">
    <%= form_with model: @contact_form, class: 'contact100-form validate-form' do |form| %>
      <span class="contact100-form-title">
        <%= I18n.t('new.form_title') %>
      </span>
      <label class="label-input100" for="first-name"><%= I18n.t('new.display_name_label') %>* </label>
      <div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate="<%= I18n.t('new.first_name_validation') %>">
        <%= form.text_field :first_name,:id =>"first-name" ,:class => "input100", :name => "first_name" ,:placeholder => I18n.t('new.first_name') %>
        <span class="focus-input100"></span>
      </div>
      <div class="wrap-input100 rs2-wrap-input100 validate-input" data-validate="<%= I18n.t('new.last_name_validation')%>">
        <%= form.text_field :last_name,:class => "input100", :name => "last_name" ,:placeholder =>I18n.t('new.last_name')%>
        <span class="focus-input100"></span>
      </div>
      <label class="label-input100" for="email"><%= I18n.t('new.email_label') %> *</label>
      <div class="wrap-input100 validate-input" data-validate="<%= I18n.t('new.email_validation') %>">
        <%= form.text_field :email,:id => "email",:class => "input100", :name => "email" ,:placeholder =>"#{I18n.t('new.example')}. example@email.com"%>
        <span class="focus-input100"></span>
      </div>
      <label class="label-input100" for="phone"><%= I18n.t('new.phone_number_label')%></label>
      <div class="wrap-input100">
        <%= form.text_field :phone,:id => "phone",:class => "input100", :name => "phone" ,:placeholder =>"#{I18n.t('new.example')}. +1 800 000000"%>
        <span class="focus-input100"></span>
      </div>
      <label class="label-input100" for="message"><%= I18n.t('new.message_label') %> *</label>
      <div class="wrap-input100 validate-input" data-validate= "<%=I18n.t('new.message_validation') %>" >
        <%= form.text_area :message,:id => "message",:class => "input100", :name => "message" ,:placeholder => I18n.t('new.message_placeholders') %>
        <span class="focus-input100"></span>
      </div>
      <div class="container-contact100-form-btn">
        <%= form.submit I18n.t('new.send_message_button'), :class => "contact100-form-btn" %>
      </div>
    <%end%>
    <div class="contact100-more flex-col-c-m ", style="background-image: url('<%= asset_pack_path 'media/images/bg-01.jpg' %>')">
      <div class="flex-w size1 p-b-47">
        <div class="txt1 p-r-25">
          <span class="lnr lnr-map-marker"></span>
        </div>
        <div class="flex-col size2">
          <span class="txt1 p-b-20">
            Address
          </span>
          <span class="txt2">
            Mada Center 8th floor, 379 Hudson St, New York, NY 10018 US
          </span>
        </div>
      </div>
      <div class="dis-flex size1 p-b-47">
        <div class="txt1 p-r-25">
          <span class="lnr lnr-phone-handset"></span>
        </div>
        <div class="flex-col size2">
          <span class="txt1 p-b-20">Lets Talk</span>
          <span class="txt3"> +1 800 1236879</span>
        </div>
      </div>
      <div class="dis-flex size1 p-b-47">
        <div class="txt1 p-r-25">
          <span class="lnr lnr-envelope"></span>
        </div>
        <div class="flex-col size2">
          <span class="txt1 p-b-20"> General Support</span>
          <span class="txt3">contact@example.com</span>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="dropDownSelect1"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application'%>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body>
    Language:- <%= link_to_unless_current "English", locale: "en" %> |
    <%= link_to_unless_current "Telugu", locale: "te" %>
    <%= yield %>
  </body>
</html>